version: "3.9"
services:
  backend:
    build:
      context: backend
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ./backend:/app
    # configure app
    environment:
      FLASK_SECRET_KEY: good_password
      FLASK_DATABASE: mongodb://root:better_password@mongo:27017
    # prevent container from exiting
    command: /bin/sh -c "while sleep 1000; do :; done"

  frontend:
    build: 
      context: frontend
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ./frontend:/app
    command: /bin/sh -c "while sleep 1000; do :; done"

  # database service
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: better_password
