version: "3.9"
services:
  backend:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/app
    # configure app
    environment:
      FLASK_SECRET_KEY: good_password
      FLASK_DATABASE: mongodb://root:better_password@mongo:27017
    # prevent container from exiting
    command: /bin/sh -c "while sleep 1000; do :; done"

  frontend:
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile.local
    ports:
      - "80:80"

  # database service
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: better_password
